#!/bin/bash

set -u
echo "only set -u !"

export IP1=some-addr
export IP2=some-addr
export IP3=some-addr
export IP4=some-addr
export IP5=some-addr
export IP6=some-addr

# using this works! even after hitting the first rate limit on the IP address,
# we can continue to the next one. only at the 3rd IP address we get a 429 Too Many Requests
# (because it's the same account). But that final problem isn't an issue for us, since we don't
# do that many requests on the same account.
export IPV6_ADDR=some-addr

# oracle cloud
# * whenever a CIDR is asked, use '::/0' to apply to all
# * open VCN (virtual cloud network) of the instances
# * add IPv6 CIDR block. let oracle generate one block for us
# * VCN > subnet > add IPv6 Prefix > add generated by Oracle with '00'
# * add subnet security rule to allow all IPv6 incoming (symmetrically also outgoing requests)
# * VCN > routing table > add IPv6 rule towards internet gateway
# * instance > VNICs > add IPv6 > auto-generated
# * restart instance
# * test with `curl -v -6 ifconfig.co`
# * use a specific outbound IPv6 address: `curl --interface <ipv6-addr> -6 ifconfig.co`


read_2fa_code_from_terminal() {
    if [[ -v VRCHAT_TOTP ]]; then
        TFA_CODE="$(oathtool --totp --base32 "$VRCHAT_TOTP")"
        export TFA_CODE
        echo "Using generated 2FA code: $TFA_CODE"
        sleep 2s # sleep a bit to simulate user duration
    else
        echo "Enter the 2FA code from your auth-app / Email:"
        read -r TFA_CODE
        export TFA_CODE
    fi
}

# manual approach
works() {
    OUT="out-$(date +%T).log"
    COOKIE_JAR_FILE="$(mktemp)"

    echo "======================= 1 ========================"
    curl --interface "$IPV6_ADDR" -6 -i -c "$COOKIE_JAR_FILE" 'https://api.vrchat.cloud/api/1/auth/user' \
        -H 'User-Agent: SP2Any/0.1.0 does-not-exist-792374@gmail.com' \
        -H 'Accept: */*' \
        -u "$VRCHAT_USERNAME:$VRCHAT_PASSWORD"

    read_2fa_code_from_terminal

    echo "======================= 2 ========================"
    RESPONSE="$(
      curl --interface "$IPV6_ADDR" -6 --no-progress-meter -i -b "$COOKIE_JAR_FILE" 'https://api.vrchat.cloud/api/1/auth/twofactorauth/totp/verify' \
        -X POST \
        -H 'User-Agent: SP2Any/0.1.0 does-not-exist-792374@gmail.com' \
        -H 'content-type: application/json' \
        --data-raw "{\"code\":\"$TFA_CODE\"}"
    )"
    
    echo "$RESPONSE"

    echo "$RESPONSE" | grep "{" > "$OUT"
}


works

# main
