services:
  sp2any-webserver:
    container_name: sp2any-webserver
    build:
      dockerfile: server.Dockerfile
      context: .
    env_file:
      - release/config/server.defaults.env
    volumes:
      - ./sp2any.json:/root/.config/sp2any/sp2any.json
    command: "--webserver --no-gui"
    restart: "on-failure:2"
    network_mode: host

  sp2any-db:
    image: postgres:17-alpine
    container_name: sp2any-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sp2any
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - sp2any-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: "on-failure:2"

volumes:
  sp2any-data:
    name: sp2any-data
