services:
  sp2any:
    build:
      dockerfile: server.Dockerfile
      context: "."
    image: "sp2any:latest"
    container_name: sp2any
    env_file:
      - release/config/server.defaults.env
      - server.env
    restart: "on-failure:2"
    networks:
      - sp2any-net

networks:
  sp2any-net:
    name: sp2any-net
    driver: bridge
