services:
  sps-status:
    build:
      dockerfile: server.Dockerfile
      context: "."
    image: "sps-status:latest"
    container_name: sps-status
    env_file:
      - defaults.env
      - server.env
    restart: always
    networks:
      - sps-status-net

networks:
  sps-status-net:
    name: sps-status-net
    driver: bridge
