services:
  sp2any-webserver:
    container_name: sp2any-webserver
    build:
      dockerfile: server.Dockerfile
      context: .
    env_file:
      - release/config/server.defaults.env
    volumes:
      - ./sp2any.json:/root/.config/sp2any/sp2any.json
    command: "--webserver --no-gui"
    restart: "on-failure:2"
    network_mode: host
  