[package]
name = "sp2any-bridge"
version = "0.1.0"
edition = "2021"
rust-version = "1.87.0"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
reqwest = { version = "0.12", features = ["json"] }
anyhow = "1"
sp2any = { path = ".." }
