name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v (e.g. v1.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust, Cargo and rustup
      uses: dtolnay/rust-toolchain@stable

    - name: Get cached Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Get cached npm packages
      uses: actions/cache@v4
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

    - name: Install prerequisites
      shell: bash
      run: ./release/ci-install-dependencies.sh

    - name: Run build script
      run: "./release/release-build.sh"

    - name: Generate changelog
      id: changelog
      run: |
        ./release/generate-changelog.sh "${{ github.ref_name }}" RELEASE_NOTES.md
        echo "notes_file=RELEASE_NOTES.md" >> $GITHUB_OUTPUT
        
        IS_PRERELEASE="$( [[ "${{ github.ref_name }}" == *"-"* ]] && echo "true" || echo "false" )"
        echo "IS_PRERELEASE=$IS_PRERELEASE" >> $GITHUB_ENV

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.DEPLOY_PR_TOKEN }}
        files: "target/release_builds/*"
        body_path: ${{ steps.changelog.outputs.notes_file }}
        prerelease: ${{ env.IS_PRERELEASE }}
        draft: false
