name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v (e.g. v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust, Cargo and rustup
      uses: dtolnay/rust-toolchain@stable

    - name: Install MinGW toolchains for Windows targets
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64-x86-64 gcc-mingw-w64-i686

    - name: Run build script
      run: "./build-binaries.sh"

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        files: "target/release_builds/*"
