name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v (e.g. v1.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Run Tests
      uses: ./.github/actions/build-test-lint
      with:
        SKIP_SETUP: false
        RUN_TESTS: false
        SPS_API_TOKEN: ${{ secrets.SPS_API_TOKEN }}
        SPS_API_WRITE_TOKEN: ${{ secrets.SPS_API_WRITE_TOKEN }}
        DISCORD_OAUTH_CLIENT_ID: ${{ secrets.DISCORD_OAUTH_CLIENT_ID }}
        DISCORD_OAUTH_CLIENT_SECRET: ${{ secrets.DISCORD_OAUTH_CLIENT_SECRET }}
        DISCORD_STATUS_MESSAGE_TOKEN: ${{ secrets.DISCORD_STATUS_MESSAGE_TOKEN }}
        VRCHAT_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
        VRCHAT_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
        VRCHAT_COOKIE: ${{ secrets.VRCHAT_COOKIE }}

    - name: Run build script
      run: "./steps/30-build-release.sh"

    - name: Configure Release
      run: |
        IS_PRERELEASE="$( [[ "${{ github.ref_name }}" == *"-"* ]] && echo "true" || echo "false" )"
        echo "IS_PRERELEASE=$IS_PRERELEASE" >> $GITHUB_ENV

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.DEPLOY_PR_TOKEN }}
        files: "target/release_builds/*"
        prerelease: ${{ env.IS_PRERELEASE }}
        draft: false
