name: Run Tests

on:
  push:
    branches: '**'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust, Cargo and rustup
        uses: dtolnay/rust-toolchain@stable

      - name: Install prerequisites
        run: |
          sudo apt update

          # Tauri
          cargo install tauri-cli --version "^2" --locked
          sudo apt-get install \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

          # MinGW toolchains for Windows targets
          sudo apt-get install -y gcc-mingw-w64-x86-64 gcc-mingw-w64-i686

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Unit tests
        run: ./test/unit-tests.sh

      - name: Webserver Integration Tests
        env:
          SPS_API_TOKEN: ${{ secrets.SPS_API_TOKEN }}
          SPS_API_WRITE_TOKEN: ${{ secrets.SPS_API_WRITE_TOKEN }}
        run: ./test/webserver.integration-tests.sh

      - name: VRC Updater Integration Tests
        env:
          SPS_API_TOKEN: ${{ secrets.SPS_API_TOKEN }}
          SPS_API_WRITE_TOKEN: ${{ secrets.SPS_API_WRITE_TOKEN }}
          VRCHAT_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
          VRCHAT_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
          VRCHAT_COOKIE: ${{ secrets.VRCHAT_COOKIE }}
        run: ./test/vrcupdater.integration-tests.sh
