name: Run Tests

on:
  # disable tests, because vrchat stuff doesn't work on github.
  # this workflow only checks, that the stuff builds so that it's cached for subsequent builds and the release.
  push:
    branches: '**'
  workflow_dispatch:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Run Tests
      uses: ./.github/actions/build-test-lint
      with:
        RUN_TESTS: false
        SPS_API_TOKEN: ${{ secrets.SPS_API_TOKEN }}
        SPS_API_WRITE_TOKEN: ${{ secrets.SPS_API_WRITE_TOKEN }}
        DISCORD_OAUTH_CLIENT_ID: ${{ secrets.DISCORD_OAUTH_CLIENT_ID }}
        DISCORD_OAUTH_CLIENT_SECRET: ${{ secrets.DISCORD_OAUTH_CLIENT_SECRET }}
        DISCORD_STATUS_MESSAGE_TOKEN: ${{ secrets.DISCORD_STATUS_MESSAGE_TOKEN }}
        VRCHAT_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
        VRCHAT_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
        VRCHAT_COOKIE: ${{ secrets.VRCHAT_COOKIE }}
