name: Update Dependencies

on:
  # disabled until further notice
  # schedule:
  #   - cron: "9 5 * * 2" # Runs every tuesday at 05:09
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust, Cargo and rustup
      uses: dtolnay/rust-toolchain@stable

    - name: Install prerequisites
      shell: bash
      run: ./steps/03-install-dependencies.sh

    - name: Update Rust dependencies
      run: |
        cargo update

    - name: Update Node dependencies
      run: |
        cd frontend
        npm install --ignore-scripts -g npm-check-updates
        ncu -u
        npm install --ignore-scripts
        cd ..

    - name: Has Changes
      id: changed
      run: |
        echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        git add .
        if git diff --staged --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Run Tests
      uses: ./.github/actions/build-test-lint
      if: steps.changed.outputs.changes == 'true'
      with:
        SKIP_SETUP: true
        SPS_API_TOKEN: ${{ secrets.SPS_API_TOKEN }}
        SPS_API_WRITE_TOKEN: ${{ secrets.SPS_API_WRITE_TOKEN }}
        DISCORD_OAUTH_CLIENT_ID: ${{ secrets.DISCORD_OAUTH_CLIENT_ID }}
        DISCORD_OAUTH_CLIENT_SECRET: ${{ secrets.DISCORD_OAUTH_CLIENT_SECRET }}
        DISCORD_STATUS_MESSAGE_TOKEN: ${{ secrets.DISCORD_STATUS_MESSAGE_TOKEN }}
        VRCHAT_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
        VRCHAT_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
        VRCHAT_COOKIE: ${{ secrets.VRCHAT_COOKIE }}

    - name: Cache Dependencies
      uses: ./.github/actions/build-test-lint
      if: steps.changed.outputs.changes == 'true'
      with:
        SKIP_TESTS: true
        SPS_API_TOKEN: ${{ secrets.SPS_API_TOKEN }}
        SPS_API_WRITE_TOKEN: ${{ secrets.SPS_API_WRITE_TOKEN }}
        DISCORD_OAUTH_CLIENT_ID: ${{ secrets.DISCORD_OAUTH_CLIENT_ID }}
        DISCORD_OAUTH_CLIENT_SECRET: ${{ secrets.DISCORD_OAUTH_CLIENT_SECRET }}
        DISCORD_STATUS_MESSAGE_TOKEN: ${{ secrets.DISCORD_STATUS_MESSAGE_TOKEN }}
        VRCHAT_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
        VRCHAT_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
        VRCHAT_COOKIE: ${{ secrets.VRCHAT_COOKIE }}

    - name: Create Pull Request
      if: steps.changed.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.DEPLOY_PR_TOKEN }}
        commit-message: "chore(deps): update dependencies"
        title: "Update Dependencies"
        body: "This PR updates the project dependencies."
        branch: dependencies/update-${{ env.CURRENT_DATE }}
        base: main

